### ISSUE TITLE
Sound notifications do not work

### ISSUE THREAD

**Issue by l-rom** [Havoc-OS/android_packages_apps_Messaging#1]
Sound notifications do not work

**Comment by dendi** [comment]
how to solve this issue? I got same problem. I cannot change whatsapp ringtone. It is assigned to the default ringtone called 
**`android.resource://com/google.android.soundpicker/string/sun_shower`**

When I try to change it to mp3, it says "wrong file, please select again"

I think this issue is related to **sound picker**?

**Comment by slayer3032** [comment]
> how to solve this issue? I got same problem. I cannot change whatsapp ringtone. It is assigned to the default ringtone called
> **`android.resource://com/google.android.soundpicker/string/sun_shower`**
> 
> When I try to change it to mp3, it says "wrong file, please select again"
> 
> I think this issue is related to **sound picker**?

I've had the same issue through multiple clean installs and updates ever switching to Havoc, half of the time my ringtones don't even fire off or use some super generic nearly inaudible ding. My settings app just crashes instead of even giving an error though...
